config/routes.rb
Chekov::Application.routes.draw do

  resources :contexts do
    get 'list',   on: :collection
    post 'clone', on: :member
    resources :stories do
      resources :suites
    end
  end

  resources :assignments
  resources :elements
  resources :releases
  resources :users

  get  'login'=>'sessions#login',         :as=>:login
  post 'authorize'=>'sessions#authorize', :as=>:authorize
  get  'logout'=>'sessions#logout',       :as=>:logout

  root 'contexts#index'

end

app/models/context.rb
class Context < ActiveRecord::Base

  belongs_to :release, touch: true

  has_many :assignments, dependent: :destroy
  has_many :checks,        through: :suites
  has_many :stories,     dependent: :destroy
  has_many :suites,        through: :stories

  scope :abc,     ->{ order('contexts.name') }
  scope :hidden,  ->{ where(visible: false)  }
  scope :visible, ->{ where(visible: true)   }

  def passed_for(browser, user = nil)
    return 0 if stories.count.zero?
    (stories.to_a.sum{|s|s.passed_for browser, user} / stories.count.to_f).round
  end

  def passed_blended(user = nil)
    return 0 if browsers.count.zero?
    (browsers.sum{|b| passed_for b, user} / browsers.count.to_f).round
  end

  def browsers
    Suite.browsers.select{|b| __send__ "#{b}?"}
  end

  def copy_into(release)
    context = release.contexts.build name: name, ie8: ie8?, ie9: ie9?, ie10: ie10?, ie11: ie11?, ff: ff?, chrome: chrome?, safari: safari?, description: description
    context.save!
    stories.each do |s|
      story = context.stories.build name: s.name, description: s.description
      story.save!
      s.elements.each do |e|
        element = story.elements.build description: e.description
        element.save!
      end
    end
    context
  end

  validates_presence_of :name, :release_id

end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  before_action :find_current_release

  # GET /
  def index
    @user = User.find params[:user_id] unless params[:user_id].blank?
  end

  # GET /contexts/list
  def list
    send_data @release.list_csv,
      type: 'text/csv; charset=iso-8859-1; header=present',
      disposition: 'attachment; filename=list.csv'
  end

  # GET /contexts/:id
  def show
    @context = @release.contexts.find params[:id]
    @user = User.find params[:user_id] unless params[:user_id].blank?
  end

  # GET /contexts/:id/edit
  def edit
    @context = @release.contexts.find params[:id]
  end

  # GET /contexts/new
  def new
    @context = @release.contexts.build
  end

  # POST /contexts
  def create
    @context = @release.contexts.build context_params
    @context.save!
    redirect_to @context
  rescue ActiveRecord::RecordInvalid
    render action: 'new'
  end

  # PUT /contexts/:id
  def update
    @context = @release.contexts.find params[:id]
    @context.update_attributes! context_params
    redirect_to @context
  rescue ActiveRecord::RecordInvalid
    render action: 'edit'
  end

  def clone
    @context = @release.contexts.find params[:id]
    clone = @context.copy_into @release
    clone.update_attribute :name, "#{clone.name} Copy"
    redirect_to clone
  end

  protected
  def context_params
    params.require(:context).permit(:name, :description, :ie8, :ie9, :ie10, :ie11, :ff, :chrome, :safari, :ios, :android, :visible)
  end

end

app/views/contexts/_form.html.haml
%p Name
%p= form.text_field :name
%p
  Browser:
  - Suite.browsers.each do |browser|
    = form.check_box browser
    = form.label browser, name_of(browser)
%p= form.text_area :description
%p
  = form.check_box :visible
  = form.label :visible, 'Visible'

app/views/contexts/edit.html.haml
%h2 
  Edit
  = @context.name

= form_for @context do |form|
  = render form
  %p= form.submit 'Update'

app/views/contexts/index.html.haml
= form_tag root_path, :method=>:get do
  %p
    %select{name: 'user_id'}
      %option{value: ''} Everyone
      - User.abc.each do |u|
        - options = {value: u.id}
        - options[:selected] = 'selected' if u == @user
        %option{options}= u.name
    = submit_tag 'Show'

= cache @release do
  %table.data
    %tr
      %th Context
      - @release.browsers.each do |browser|
        %th.percent= browser
      %th.percent Blended
    - @release.contexts.visible.abc.each do |context|
      = cache context do
        %tr
          %td.title= link_to context.name, context
          - @release.browsers.each do |browser|
            - if context.__send__ "#{browser}?"
              - if context.suites.for_browser(browser).from_user(@user).count == 0
                %td
              - else
                %td{style: "background-color: #{colorize context.passed_for(browser, @user)}"}
                  = label_for context.passed_for(browser, @user)
            - else
              %td.inactive

          - if context.browsers.count == 0
            %td.inactive
          - elsif context.suites.from_user(@user).count == 0
            %td
          - else
            %td.strong{style: "background-color: #{colorize context.passed_blended(@user)}"}
              = label_for context.passed_blended(@user)

    %tr.strong
      %td.title Total
      - @release.browsers.each do |browser|
        - if @release.contexts.select{|c|c.browsers.include?(browser)}.count == 0
          %td.inactive
        - elsif @release.suites.for_browser(browser).from_user(@user).count == 0
          %td
        - else
          %td{style: "background-color: #{colorize @release.passed_for(browser, @user)}"}= @release.passed_for browser, @user
      - if @release.suites.from_user(@user).count == 0
        %td
      - else
        %td{style: "background-color: #{colorize @release.passed_blended}"}= label_for @release.passed_blended(@user)

%p= link_to 'New Context', new_context_path

- if @release.contexts.hidden.any?
  %p Hidden Contexts:
  %ul
    - @release.contexts.hidden.each do |c|
      %li= link_to c.name, [:edit, c]

app/views/contexts/new.html.haml
%h2 
  New Context for
  = @release.name

= form_for @context do |form|
  = render form
  %p= form.submit 'Create'

app/views/contexts/show.html.haml
%h2= @context.name

%p= @context.description

%p= link_to 'Edit Context', [:edit, @context]

= form_tag @context, :method=>:get do
  %p
    %select{name: 'user_id'}
      %option{value: ''} Everyone
      - User.abc.each do |u|
        - options = {value: u.id}
        - options[:selected] = 'selected' if u == @user
        %option{options}= u.name
    = submit_tag 'Show'

= cache @context do
  %table.data
    %tr
      %th Story
      - @context.browsers.each do |browser|
        %th.percent= browser
      %th.percent Blended
    - @context.stories.abc.each do |story|
      = cache story do
        %tr
          %td.title
            = story.name
            .edit= link_to 'Edit', [@context, story]
          - @context.browsers.each do |browser|
            - color = {class: 'clickable'}
            - color[:style] = "background-color: #{colorize story.passed_for(browser, @user)}" unless story.suites.for_browser(browser).from_user(@user).count == 0
            %td.highlight{color}= link_to label_for(story.passed_for(browser, @user)), new_context_story_suite_path(@context, story, 'suite[browser]'=>browser)
          - if story.suites.from_user(@user).count == 0
            %td
          - else
            %td.strong{style: "background-color: #{colorize story.passed_blended(@user)}"}= label_for story.passed_blended(@user)

    %tr.strong
      %td.title Total
      - @context.browsers.each do |browser|
        - if @context.suites.for_browser(browser).from_user(@user).count == 0
          %td
        - else
          %td{style: "background-color: #{colorize @context.passed_for(browser, @user)}"}= label_for @context.passed_for(browser, @user)
      - if @context.suites.from_user(@user).count == 0
        %td
      - else
        %td{style: "background-color: #{colorize @context.passed_blended(@user)}"}= label_for (@context.passed_blended(@user))

%p= link_to 'New Story', new_context_story_path(@context)


%br
%br
%table
  %tr
    %th User
    - @context.browsers.each do |browser|
      %th= browser
  - User.abc.each do |user|
    %tr
      %td= user.name
      - @context.browsers.each do |browser|
        %td
          = form_for Assignment.new, remote: true do |f|
            = hidden_field_tag :context_id, @context.id
            = hidden_field_tag :user_id, user.id
            = hidden_field_tag :browser, browser
            = check_box_tag 'assignment', 'true', user.assigned?(@context, browser), user_id: user.id, context_id: @context.id, browser: browser, class: 'assignment'


%br
%br
%p= button_to 'Clone', [:clone, @context], method: :post, data: { confirm: 'Are you sure?' }